### ISSUE TITLE
Add code to /etc/inittab

### ISSUE THREAD

**Issue by jphilipsen05** [OPMDG/opm-issues#1]
In your install instructions most it states that you need to add code to the end of /etc/inittab. I am working on a Ubuntu system that uses upstart and I need a file in /etc/init to configure upstart to work with the opmdg software. I can not figure out how to write the code to work in /etc/init. Any advice would be helpful.

Code to add:

<code>d1:23:respawn:/usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl --daemon --config /usr/local/etc/nagios_dispatcher.conf</code>

Thanks,
Josah

**Comment by ioguix** [comment]
Hi,

This initscript intent to keep the nagios_dispatcher up and running even if it crash or if it stopped.

If your system use upstart, you need to create an upstart script. Given my little experience with upstart, here is a skeleton you can test/improve:

```
# nagios_dispatcher - Start nagios_dispatcher
 
description ​  "nagios_dispatcher for OPM"​	 
author ​       "OPMDG"​	 
 
start on runlevel [2345]
stop on runlevel [016]
 
setuid nagios
respawn
 
pre-start exec logger -i -t "nagios_dispatcher"​ "INFO: Starting"​
post-start exec logger -i -t "nagios_dispatcher"​ "INFO: Running"​ 
 
exec /usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl --demon --config /usr/local/etc/nagios_dispatcher.conf
#exec su -s /bin/sh -c 'exec "​$0"​ "​$@"'​ postgres -- /usr/bin/perl -w /usr/local/bin/nagios_dispatcher.pl --config /usr/local/etc/nagios_dispatcher.conf

pre-stop exec logger -i -t "nagios_dispatcher"​ "INFO: Stopping"​	 
post-stop exec logger -i -t "nagios_dispatcher"​ "INFO: Stopped"​
```

I'm not sure how to start nagios_dispatcher exactly, if it can go to background as deamon or not, but I guess it should.
